### ISSUE TITLE
SdkWorkflow.fetch is broken

### ISSUE THREAD

**Issue by georgesnelling** [lyft/flyte#103]
wf = SdkWorkflow.fetch(project, domain, name, version)

returns:
Traceback (most recent call last):
  File "app/workflows/registerar_workflow.py", line 70, in <module>
    bump_cache_versions.unit_test(project="flytekit", domain="development", name="tests.flytekit.common.workflows.batch.BatchTasksWorkflow", version="49aa6fefb9d718b2cceb418b56987a4bd68eae18", desired_cache_version="")
  File "/Users/hamabuelfutuh/.virtualenvs/flyteexamples/lib/python2.7/site-packages/flytekit/common/exceptions/scopes.py", line 160, in system_entry_point
    _reraise(ex.type, ex.value, ex.traceback)
  File "/Users/hamabuelfutuh/.virtualenvs/flyteexamples/lib/python2.7/site-packages/flytekit/common/exceptions/scopes.py", line 163, in system_entry_point
    return wrapped(*args, **kwargs)
  File "/Users/hamabuelfutuh/.virtualenvs/flyteexamples/lib/python2.7/site-packages/flytekit/common/workflow.py", line 169, in fetch
    sdk_workflow = cls.promote_from_model(admin_workflow.closure.compiled_workflow.primary.template)
  File "/Users/hamabuelfutuh/.virtualenvs/flyteexamples/lib/python2.7/site-packages/flytekit/common/workflow.py", line 189, in promote_from_model
    for n in base_model.nodes
  File "/Users/hamabuelfutuh/.virtualenvs/flyteexamples/lib/python2.7/site-packages/flytekit/common/workflow.py", line 189, in <dictcomp>
    for n in base_model.nodes
  File "/Users/hamabuelfutuh/.virtualenvs/flyteexamples/lib/python2.7/site-packages/flytekit/common/nodes.py", line 188, in __init__
    non_none_entities
flytekit.common.exceptions.user.FlyteAssertion: An SDK node must have one underlying entity specified at once.  Received the following entities: []

**Comment by wild-endeavor** [comment]
This has been fixed.
